# Generated by Django 3.0.4 on 2020-03-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.TextField(default='More than 0 baht'),
        ),
    ]
