# Generated by Django 3.0.4 on 2020-03-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='materials',
            field=models.TextField(blank=True),
        ),
    ]
